default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: voting_development
  username: postgres
  password: 3441

staging:
  <<: *default
  database: voting_staging
  username: postgres
  password: 3441

production:
  <<: *default
  database: voting_production
  username: postgres
  password: 3441